# Generated by Django 5.1.2 on 2024-10-19 15:49

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('request', 'Request'), ('pending', 'Pending'), ('approve', 'Approve'), ('cancel', 'Cancel')], max_length=10)),
                ('order_type', models.CharField(choices=[('Mug', 'Mug'), ('Magic Mug', 'Magic Mug'), ('T-shirt printing', 'T-shirt printing'), ('Tableau', 'Tableau'), ('Sticker', 'Sticker')], max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screenshot', models.ImageField(upload_to=orders.models.get_customer_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=6, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
