# Generated by Django 5.1.2 on 2024-10-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_expense_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0010375494071146246, max_digits=10),
            preserve_default=False,
        ),
    ]
