# Generated by Django 5.1.2 on 2024-11-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
