# Generated by Django 5.1.2 on 2024-11-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_order_delete_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='review',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/screenshots/'),
        ),
    ]
