# Generated by Django 5.1.2 on 2024-11-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name_customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
