# Generated by Django 5.1.2 on 2024-10-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraction_apps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraction',
            old_name='apps',
            new_name='app_name',
        ),
    ]
