# Generated by Django 5.1.2 on 2024-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.TextField(blank=True, max_length=6, unique=True),
        ),
    ]
