# Generated by Django 5.1.2 on 2024-10-19 11:35

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('interest', models.CharField(choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Other', 'Other')], max_length=20)),
                ('how_did_we_know', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20)),
                ('screenshot', models.ImageField(upload_to=customers.models.get_customer_image_upload_to)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=6, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
