# Generated by Django 5.1.2 on 2024-10-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='apps',
            field=models.CharField(choices=[('accounts', 'accounts'), ('customers', 'customers'), ('finances', 'finances'), ('orders', 'orders'), ('review', 'review')], default=0.010784313725490198, max_length=10),
            preserve_default=False,
        ),
    ]
