# Generated by Django 5.1.2 on 2024-10-19 18:38

import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='screenshot',
            field=models.ImageField(default='default/screenshot.png', upload_to=finances.models.get_customer_image_upload_to),
            preserve_default=False,
        ),
    ]
